branches:
  only:
    - master

language: node_js
node_js:
  - "node"

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    recipients:
      - campagni@extendi.it
      - dimonaco@extendi.it
    on_success: always
    on_failure: always
